#!/bin/bash
#
# Require branch name having a pre-defined prefix.

set -e

if [ -z "$TERM" ] || [ "$TERM" = "dumb" ]; then
    export TERM="ansi"
fi

organization="hooloovoodoo"
valid_prefixes=("feature" "bugfix" "release")

# retrieve git config
remote_url=$(git config --get remote.origin.url)

# extract repo owner
if [[ $remote_url == git@* ]]; then
  owner="$(echo "${remote_url}" | awk -F '[:/]' '{print $2}')"
else
  owner=$(echo "${remote_url}" | awk -F '/' '{print $4}')
fi

bold=$(tput bold)
normal=$(tput sgr0)

# if repo remote is within hooloovoodoo, check branch name
if [[ "${owner}" == "${organization}" ]]; then

  # check each commit
  while read -r local_ref; do
    branch_name=$(echo "${local_ref}" | awk -F 'heads/' '{print $NF}')
    for prefix in "${valid_prefixes[@]}"; do
      if [[ "$branch_name" == "$prefix"* ]]; then
        exit 0
      fi
    done

    echo "${bold}ERROR${normal} |"
    echo "${bold}ERROR${normal} | Branch name must start with one of the prefixes: ${bold}${valid_prefixes[*]}${normal}"
    echo "${bold}ERROR${normal} |"
    exit 1
  done
fi

exit 0

